//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AimRobotLite.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AimRobotLite.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.gametools.network/.
        /// </summary>
        internal static string DataApiFromGametool {
            get {
                return ResourceManager.GetString("DataApiFromGametool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;log4net&gt;
        ///  &lt;root&gt;
        ///    &lt;level value=&quot;DEBUG&quot; /&gt;
        ///    &lt;appender-ref ref=&quot;ConsoleAppender&quot; /&gt;
        ///    &lt;appender-ref ref=&quot;FileAppender&quot; /&gt;
        ///    &lt;appender-ref ref=&quot;WinFormConsoleAppender&quot; /&gt;
        ///  &lt;/root&gt;
        ///
        ///  &lt;!-- 鎺у埗鍙拌緭鍑洪厤缃?--&gt;
        ///  &lt;appender name=&quot;ConsoleAppender&quot; type=&quot;log4net.Appender.ConsoleAppender&quot;&gt;
        ///    &lt;layout type=&quot;log4net.Layout.PatternLayout&quot;&gt;
        ///      &lt;conversionPattern value=&quot;%date %-5level ---asds [%thread] [%logger] %message%newline&quot; /&gt;
        ///    &lt;/layout&gt;
        ///  &lt;/appende [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string log4net {
            get {
                return ResourceManager.GetString("log4net", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIM ROBOT LITE IS A ROBOT PROGRAM FOR BFV, AND THE ARL ROBOT PROGRAM IS FREE TO EVERYONE AND WILL NOT BE CHARGED IN ANY WAY. NOW IS VERSION 1.14.514..
        /// </summary>
        internal static string RobotBroadcast_text1 {
            get {
                return ResourceManager.GetString("RobotBroadcast.text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIM ROBOT LITE是一款战地5机器人程序，支持拓展开发功能。ARL程序免费提供给所有人，并且不会以任何方式收费。当前版本1.14.514。.
        /// </summary>
        internal static string RobotBroadcast_text2 {
            get {
                return ResourceManager.GetString("RobotBroadcast.text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1、AIM ROBOT LITE (以下简称ARL) 是一个基于Robot Mini的机器人增强程序。ARL程序不会也不打算增加带有盈利性质的功能。
        ///2、ARL程序并无注入游戏等操作功能，原则上不会因为ARL程序本身而被封禁，但仍不保证其安全性，如果你在使用ARL时被封禁了，ARL程序和ARL作者不会对此负责。
        ///3、ARL程序免费发布给所有人，作者不会以ARL程序的名义收取带有目的性质的收费（但你可以在爱发电上赞助这个程序，不过这个赞助不会让你获得任何东西）。
        ///4、ARL程序将会在未来的某一天开源（已与相关人士沟通）。.
        /// </summary>
        internal static string statement {
            get {
                return ResourceManager.GetString("statement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.0.4.
        /// </summary>
        internal static string version {
            get {
                return ResourceManager.GetString("version", resourceCulture);
            }
        }
    }
}
