//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AimRobotLite.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AimRobotLite.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 https://api.gametools.network/ 的本地化字符串。
        /// </summary>
        internal static string DataApiFromGametool {
            get {
                return ResourceManager.GetString("DataApiFromGametool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;log4net&gt;
        ///  &lt;root&gt;
        ///    &lt;level value=&quot;DEBUG&quot; /&gt;
        ///    &lt;appender-ref ref=&quot;ConsoleAppender&quot; /&gt;
        ///    &lt;appender-ref ref=&quot;FileAppender&quot; /&gt;
        ///    &lt;appender-ref ref=&quot;WinFormConsoleAppender&quot; /&gt;
        ///  &lt;/root&gt;
        ///
        ///  &lt;!-- 鎺у埗鍙拌緭鍑洪厤缃?--&gt;
        ///  &lt;appender name=&quot;ConsoleAppender&quot; type=&quot;log4net.Appender.ConsoleAppender&quot;&gt;
        ///    &lt;layout type=&quot;log4net.Layout.PatternLayout&quot;&gt;
        ///      &lt;conversionPattern value=&quot;%date %-5level ---asds [%thread] [%logger] %message%newline&quot; /&gt;
        ///    &lt;/layout&gt;
        ///  &lt;/appende [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string log4net {
            get {
                return ResourceManager.GetString("log4net", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AIM ROBOT LITE IS A ROBOT PROGRAM FOR BFV, AND THE ARL ROBOT PROGRAM IS FREE TO EVERYONE AND WILL NOT BE CHARGED IN ANY WAY. NOW IS VERSION 1.14.514. 的本地化字符串。
        /// </summary>
        internal static string RobotBroadcast_text1 {
            get {
                return ResourceManager.GetString("RobotBroadcast.text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AIM ROBOT LITE是一款战地5机器人程序，支持拓展开发功能。ARL程序免费提供给所有人，并且不会以任何方式收费。当前版本1.14.514。 的本地化字符串。
        /// </summary>
        internal static string RobotBroadcast_text2 {
            get {
                return ResourceManager.GetString("RobotBroadcast.text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1、AIM ROBOT LITE (以下简称ARL) 是一个基于Robot Mini的机器人增强程序。ARL程序不会也不打算增加带有盈利性质的功能。
        ///2、ARL程序并无注入游戏等操作功能，原则上不会因为ARL程序本身而被封禁，但仍不保证其安全性，如果你在使用ARL时被封禁了，ARL程序和ARL作者不会对此负责。
        ///3、ARL程序免费发布给所有人，作者不会以ARL程序的名义收取带有目的性质的收费（但你可以在爱发电上赞助这个程序，不过这个赞助不会让你获得任何东西）。
        ///4、ARL程序将会在未来的某一天开源（已与相关人士沟通）。 的本地化字符串。
        /// </summary>
        internal static string statement {
            get {
                return ResourceManager.GetString("statement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 2.0.0 的本地化字符串。
        /// </summary>
        internal static string version {
            get {
                return ResourceManager.GetString("version", resourceCulture);
            }
        }
    }
}
